apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit
spec:
  template:
    spec:
      containers:
      - name: streamlit-client
        env:
        - name: TAVILY_SEARCH_API_KEY
          $patch: delete
