apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - maas-private-secret.yaml
  
generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: run-config
    behavior: replace
    files:
      - config.yaml=run.yaml

patchesStrategicMerge:
  - patch-llama-stack-deploy.yaml