apiVersion: v1
kind: Secret
metadata:
  name: maas-env-secret
type: Opaque
stringData:
  MAAS_URL: https://xxxxxxxxx.com/v1
  MAAS_API_TOKEN: xxxxxxxxxxxxxxxxxxxxx
  MAAS_MODEL_NAME: my-model-name
  # Options llama-3b, granite
  MAAS_MODEL_TYPE: llama-3b
